### ISSUE TITLE
Upgrading to v1.11.2 breaks the unit test of our (lonely) streaming method

### ISSUE THREAD

**Issue by PierrickVoulet** [googleapis/gax-php#363]
#### Environment details

  - OS: Linux 64
  - PHP version: 8.0.1
  - Package name and version: gax-php, 1.11.2

#### Steps to reproduce

1. Checkout the source code of [`google-ads-php`](https://github.com/googleads/google-ads-php).
2. Change the version of the dependency `gax-php` to `1.10.0` in the [`composer.json`](https://github.com/googleads/google-ads-php/blob/main/composer.json#L7)
3. Run `composer update`
4. Run the PHPUnit test that was generated based on `google-ads` protos [`Google\\Ads\\GoogleAds\\V9\\Services\\GoogleAdsServiceClientTest::searchStreamExceptionTest`](https://github.com/googleads/google-ads-php/blob/main/tests/Google/Ads/GoogleAds/V9/Services/GoogleAdsServiceClientTest.php#L267).
4. It passes
5. Change the version of the dependency `gax-php` to `1.11.2` in the [`composer.json`](https://github.com/googleads/google-ads-php/blob/main/composer.json#L7)
6. Run `composer update`
7. Run the PHPUnit test again.
8. It fails with the following error

```php
TypeError : Google\Protobuf\Internal\RepeatedField::offsetExists(): Argument #1 ($index) must be of type int, string given
 /usr/local/google/home/pierrick/git/google-ads-php/src/Google/Ads/GoogleAds/Lib/V9/GoogleAdsExceptionTrait.php:47
 /usr/local/google/home/pierrick/git/google-ads-php/src/Google/Ads/GoogleAds/Lib/V9/ServerStreamingGoogleAdsExceptionMiddleware.php:96
 /usr/local/google/home/pierrick/git/google-ads-php/src/Google/Ads/GoogleAds/Lib/V9/ServerStreamingGoogleAdsResponseMetadataCallable.php:63
 /usr/local/google/home/pierrick/git/google-ads-php/tests/Google/Ads/GoogleAds/V9/Services/GoogleAdsServiceClientTest.php:290
```

In this particular case an `ApiException` is thrown with the `metadata` field typed as `RepeatedField` with `1.11.2` which was not the case before (I believe it was a keyed array in the version `1.10.0`).

**Comment by PierrickVoulet** [comment]
FYI @fiboknacky

**Comment by PierrickVoulet** [comment]
Not sure if that helps but debugging the failing unit test, I found that the `ApiException` instance is not created in the same way depending on the version of `gax-php` being used.

`1.10.0`: It uses the method `createFromStdClass` and the `metadata` is `NULL`.

![image](https://user-images.githubusercontent.com/6769971/150593413-efd8075b-5789-4022-b501-21efbd874867.png)

`1.11.2`: It uses the method `createFromRpcStatus` and the `metadata` is got from `status` and it is a `RepeatedField`.

![image](https://user-images.githubusercontent.com/6769971/150593451-64759edd-0806-41d1-94a0-3e162a1ac336.png)

**Comment by noahdietz** [comment]
That definitely helps! That looks like the root cause.

**Comment by noahdietz** [comment]
Actually, in looking at the `create` [documentation](https://github.com/googleapis/gax-php/blob/79af83504a30cbada97531208b823d041f73abb9/src/ApiException.php#L147), the `$metadata` may either be a PHP array OR a RepeatedField. So the fact that this is a RepeatedField is allowed.

**Comment by noahdietz** [comment]
However, the documentation for `ApiException` [constructor](https://github.com/googleapis/gax-php/blob/79af83504a30cbada97531208b823d041f73abb9/src/ApiException.php#L55) indicates `$metadata` should be an `array`.

hmm.

**Comment by noahdietz** [comment]
Ok so we are thinking that the this is a bug in gax-php that has kind of been lurking.

`ApiException::create` is documented as accepting `[]mixed|RepeatedField` for `$metadata`. That `$metadata` value is passed to `ApiException::_construct` untouched. `ApiException::_construct` documents that it expects `$metadata` to be an `array`, and `ApiException::getMetadata` documents the return type i.e. `$metadata` is `[]mixed`. 

So the bug is that `ApiException::create` needs to convert `$metadata` that's `instanceof RepeatedField` into an `array` prior to constructing the `ApiException`.

The problem was introduced because  `ServerStream::readAll` was changed to construct an exception via `ApiException::createFromRpcStatus` whereas it was `ApiException::createFromStdClass` (a gRPC specific type) before. The former (the code recently released) supplies the `Google/Rpc/Status::getDetails()` directly to `ApiException::create`. Since it isn't "massaged" to the `array` type as I mentioned earlier, this whole issue popped up. 

@bshaffer

**Comment by noahdietz** [comment]
Ok we've got a fix planned. It will come early next week. Sorry about the breakage, please continue to use 1.10 for now.
