### ISSUE TITLE
v1.34.0 breaks the Google Ads API PHP users

### ISSUE THREAD

**Issue by fiboknacky** [googleapis/gax-php#514]
Copied from https://github.com/googleads/google-ads-php/issues/981.

#### Environment details

- OS: Linux 5.15.0-91-generic 101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64
- PHP version: PHP 8.2.14
- Package name and version: googe/auth v1.34.0

#### Steps to reproduce

After upgrading `google/auth` to v1.34.0, it seems to break the Google Ads API users because the `developer-token` header isn't sent anymore.
This header is sent as part of the middleware in [this trait](https://github.com/googleads/google-ads-php/blob/a98f30fd7399f6505c5193c74cc7873acbcbedc4/src/Google/Ads/GoogleAds/Lib/V15/GoogleAdsGapicClientTrait.php).

**Comment by bshaffer** [comment]
Okay I figured it out - it has to do with [this change](https://github.com/googleapis/gax-php/commit/5a26facad5c2e5c30945987c422bb78a3fffb9b1#diff-a88e790f67676924a3112580db660b0f21e735035ae7b5ab46a0cfa03e8cd1b3R244), where we only call `modifyClientOptions` for V1 clients.

This was done because, since `modifyClientOptions` is private, and our new clients are `final`, it was assumed that there was no way for this method to be called. But as this method is [being called by ads](https://github.com/googleads/google-ads-php/blob/a98f30fd7399f6505c5193c74cc7873acbcbedc4/src/Google/Ads/GoogleAds/Lib/V15/GoogleAdsGapicClientTrait.php#L50), this assumption is wrong (I believe the trait is being added in post-processing`, which allows this to happen for Ads specifically).

The fix is to remove the conditional here and call `modifyClientOptions` for all clients

**Comment by fiboknacky** [comment]
Thanks so much!
